# 🧩 Reto 3 – Oxígeno disuelto
**Objetivo:** evaluar riesgo ecológico según oxígeno disuelto.

**Datos:** `../data/muestras_calidad_agua.csv`

### Pasos
1. Carga el CSV en `df`.
2. Extrae `sitio` y `oxigeno`.
3. Crea `nivel_oxigeno` (bajo/medio/alto).
4. Crea `riesgo_biologico` (⚠ si oxígeno < 5).
5. Filtra y exporta `resultado_oxigeno.csv`.

> **Reto adicional:** porcentaje de sitios con riesgo.

In [5]:
# Escribe tu código aquí
import pandas as pd

df = pd.read_csv("../data/muestras_calidad_agua.csv")
print("vista previa del archivo cargado")
display(df.head(10))

vista previa del archivo cargado

                           sitio   pH  oxigeno  temperatura
0                 Río Subachoque  7.2      7.8         18.5
1    Quebrada Honda (Facatativá)  6.3      6.2         19.4
2           Río Botello (Madrid)  6.8      5.9         22.7
3   Afluente San José (El Rosal)  7.9      8.3         20.1
4                    Río Villeta  8.7      6.1         28.3
5  Quebrada Cune (San Francisco)  6.0      4.5         25.2
6            Río Tobia (Nocaima)  7.4      5.2         26.9
7       Quebrada Negra (La Vega)  7.6      7.0         24.4
8          Río Bahamón (Sasaima)  8.1      6.7         27.6
9        Río Guayuriba (La Mesa)  5.9      4.8         30.5

In [7]:
sitio_oxigeno_10_df = df[["sitio", "oxigeno"]].head(10)
display(sitio_oxigeno_10_df)

                           sitio  oxigeno
0                 Río Subachoque      7.8
1    Quebrada Honda (Facatativá)      6.2
2           Río Botello (Madrid)      5.9
3   Afluente San José (El Rosal)      8.3
4                    Río Villeta      6.1
5  Quebrada Cune (San Francisco)      4.5
6            Río Tobia (Nocaima)      5.2
7       Quebrada Negra (La Vega)      7.0
8          Río Bahamón (Sasaima)      6.7
9        Río Guayuriba (La Mesa)      4.8

In [8]:
max_oxigeno = df["oxigeno"].max()
min_oxigeno = df["oxigeno"].min()

In [9]:
max_oxigeno,min_oxigeno

(np.float64(8.3), np.float64(4.5))

In [10]:
import numpy as np

def categorize_oxigeno(oxigeno):
    if oxigeno > 6:
        return 'Alto'
    elif oxigeno < 5:
        return 'Bajo'
    else:
        return 'Medio'

df['Nivel_Oxigeno'] = df['oxigeno'].apply(categorize_oxigeno)
display(df[['sitio', 'oxigeno', 'Nivel_Oxigeno']].head(10))

                           sitio  oxigeno Nivel_Oxigeno
0                 Río Subachoque      7.8          Alto
1    Quebrada Honda (Facatativá)      6.2          Alto
2           Río Botello (Madrid)      5.9         Medio
3   Afluente San José (El Rosal)      8.3          Alto
4                    Río Villeta      6.1          Alto
5  Quebrada Cune (San Francisco)      4.5          Bajo
6            Río Tobia (Nocaima)      5.2         Medio
7       Quebrada Negra (La Vega)      7.0          Alto
8          Río Bahamón (Sasaima)      6.7          Alto
9        Río Guayuriba (La Mesa)      4.8          Bajo

In [11]:
df['riesgo_biológico'] = np.where(df['oxigeno'] < 5, 'Sí', 'No')
display(df[['sitio', 'oxigeno', 'riesgo_biológico']].head(10))

                           sitio  oxigeno riesgo_biológico
0                 Río Subachoque      7.8               No
1    Quebrada Honda (Facatativá)      6.2               No
2           Río Botello (Madrid)      5.9               No
3   Afluente San José (El Rosal)      8.3               No
4                    Río Villeta      6.1               No
5  Quebrada Cune (San Francisco)      4.5               Sí
6            Río Tobia (Nocaima)      5.2               No
7       Quebrada Negra (La Vega)      7.0               No
8          Río Bahamón (Sasaima)      6.7               No
9        Río Guayuriba (La Mesa)      4.8               Sí

In [21]:
# Filtrar por riesgo_biológico 'Sí'
filtered_df = df[df['riesgo_biológico'] == 'Sí']

# Seleccionar solo las columnas deseadas antes de exportar
filtered_df[['sitio', 'oxigeno', 'riesgo_biológico']].to_csv('resultado_oxigeno.csv', index=False)

print("DataFrame filtrado exportado a 'resultado_oxigeno.csv'")

DataFrame filtrado exportado a 'resultado_oxigeno.csv'

In [22]:
# Calcular el número total de sitios
total_sitios = len(df)

# Calcular el número de sitios con riesgo biológico 'Sí'
sitios_con_riesgo = len(df[df['riesgo_biológico'] == 'Sí'])

# Calcular el porcentaje
porcentaje_riesgo = (sitios_con_riesgo / total_sitios) * 100

print(f"El porcentaje de sitios con riesgo biológico es: {porcentaje_riesgo:.2f}%")

El porcentaje de sitios con riesgo biológico es: 20.00%